#!/bin/sh
TESTS_PATH="../m68k-tests/"
PREFIX="gen-opcode-"
if [ "$1" = "" ]
then
    (cd $TESTS_PATH/ && ls ${PREFIX}*.bin.bz2) | while read file
    do
        tmp=${file#${PREFIX}}
        echo -n "${tmp%.bin.bz2} "
    done
    echo
    exit 0
fi

bzcat "$TESTS_PATH/${PREFIX}$1.bin.bz2" | ./m68k-tester
